static void __device_stub__Z15check_gm_kernelPj(unsigned *);
static void __device_stub__Z9test_copyPjS_(unsigned *, unsigned *);
static void __device_stub__Z21vlc_encode_kernel_gm0PjPKjS1_S_(unsigned *, const unsigned *, const unsigned *, unsigned *);
static void __device_stub__Z21vlc_encode_kernel_gm1PjPKjS1_S_(unsigned *, const unsigned *, const unsigned *, unsigned *);
static void __device_stub__Z21vlc_encode_kernel_gm2PjPKjS1_S_(unsigned *, const unsigned *, const unsigned *, unsigned *);
static void __device_stub__Z21vlc_encode_kernel_sm1PjPKjS1_S_(unsigned *, const unsigned *, const unsigned *, unsigned *);
static void __device_stub__Z21vlc_encode_kernel_sm4PjPKjS1_S_(unsigned *, const unsigned *, const unsigned *, unsigned *);
static void __device_stub__Z21vlc_encode_kernel_dptPjS_S_S_S_(unsigned *, unsigned *, unsigned *, unsigned *, unsigned *);
static void __device_stub__Z22vlc_encode_kernel_dptaPjS_S_S_S_(unsigned *, unsigned *, unsigned *, unsigned *, unsigned *);
static void __device_stub__Z22vlc_encode_kernel_dpt2PjS_S_S_S_(unsigned *, unsigned *, unsigned *, unsigned *, unsigned *);
static void __device_stub__Z23vlc_encode_kernel_dpt2bPjS_S_S_S_(unsigned *, unsigned *, unsigned *, unsigned *, unsigned *);
static void __device_stub__Z11scan_kernelPjS_(unsigned *, unsigned *);
static void __device_stub__Z24vlc_encode_kernel_sm1refPjPKjS1_S_(unsigned *, const unsigned *, const unsigned *, unsigned *);
